name: golang_staging

services:
  db:
    image: postgres:16
    env_file:
      - app.env
    volumes:
      - ../pgsql_volumes/golang_staging/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staging_user"]
      interval: 10s
      timeout: 5s
      retries: 2

  redis:
    image: redis:latest

  backend:
    image: golang_staging
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - app.env

  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "7001:80"
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/nginx.conf
