name: golang

services:
  db:
    image: postgres:16
    env_file:
      - ./app.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  backend:
    image: golang_backend
    build:
      context: .
    depends_on:
      - db
      - redis
    env_file:
      - ./app.env
    
  nginx:
    image: nginx:latest
    ports:
      - "7000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
