name: golang_staging

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
      POSTGRES_PORT: 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 10s
          retries: 2

  redis:
    image: redis:latest

  backend:
    image: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "8001:8019"
    env_file:
      - app.env

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data: