name: Build, Test, and Deploy for Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t golang_staging .
      - name: Save and compress Docker image
        run: docker save golang_staging | gzip > golang_staging.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: golang_staging
          path: golang_staging.tar.gz

  upload_docker_image:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.event.repository.fork == false
    environment:
      name: "development"
      url: ${{ vars.URL }}
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: golang_staging
          path: .

      - name: Copy image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: golang_staging.tar.gz
          target: "/tmp"

  build_and_test:
    runs-on: ubuntu-latest
    environment: staging
    env:
      TEST_USERNAME: postgres
      TEST_PASSWORD: password
      TEST_DB_NAME: db_name
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_CONNECTION: pgsql
      TEST_TIMEZONE: Africa/Lagos
      TEST_SSLMODE: disable
      TEST_MIGRATE: true
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.TEST_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.TEST_PASSWORD }}
          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Create app config file
        run: cp app-sample.env app.env
      - name: Build the application
        run: go build -o staging_app
      - name: Run the application
        run: nohup ./staging_app > /dev/null 2>&1 &
      - name: Wait for application to start
        run: |
          for i in {1..30}; do
            curl -s http://localhost:8019 && break
            sleep 1
          done
      - name: Run All Tests
        run: go test ./... -timeout 300s

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push'
    environment: staging

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export APPROOT=~/deployments/staging
            mkdir -p $APPROOT
            cd $APPROOT

            if [ -d "$APPROOT/.git" ]; then
              # Navigate to the repository directory and pull changes
              cd $APPROOT || { echo "Failed to navigate to web root directory"; exit 1; }
              git reset --hard HEAD || { echo "Failed to reset local changes"; exit 1; }
              git pull origin staging || { echo "Failed to pull latest changes"; exit 1; }
            else
              git clone -b staging https://github.com/${{ github.repository}} . || { echo "Failed to clone repository"; exit 1; }
            fi

            bash ./scripts/deploy_app.sh staging https://github.com/${{ github.repository}} \
              SERVER_PORT=${{ secrets.SERVER_PORT }} \
              DB_NAME=${{ secrets.DB_NAME }} \
              USERNAME=${{ secrets.USERNAME }} \
              APP_NAME="staging" \
              APP_URL="https://staging.api-golang.boilerplate.hng.tech" \
              REDIS_PORT=${{ secrets.REDIS_PORT }} \
              REDIS_HOST=${{ secrets.REDIS_HOST }} \
              REDIS_DB="0" \
              GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} \
              FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} \
              SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
              MAIL_SERVER=${{ secrets.MAIL_SERVER }} \
              MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
              MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              MAIL_PORT=${{ secrets.MAIL_PORT }} \
              MIGRATE=true

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            gunzip -c /tmp/golang_staging.tar.gz | docker load
            rm -f /tmp/golang_staging.tar.gz
            cd ~/deployments/staging
            docker compose -f docker-compose-staging.yml up -d